apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://0.0.0.0:40303
  name: k3d-cluster
contexts:
- context:
    cluster: k3d-cluster
    user: admin@k3d-cluster
  name: k3d-cluster
current-context: k3d-cluster
kind: Config
preferences: {}
users:
- name: admin@k3d-cluster
  user:
    client-certificate-data: 
    client-key-data: 
